/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { InsuranceBuilding, ComparableBuilding } from "./types";

export const insuranceBuildings: InsuranceBuilding[] = [
  {
    id: "dangsan",
    name: "당산 우체국보험회관",
    city: "당산",
    address: "서울특별시 영등포구 선유동2로 6",
    coordinates: { x: 34, y: 32 }, // Seoul area north
    builtYear: 2021,
    floors: {
      underground: 4,
      ground: 13,
    },
    landAreaSqm: 2150,
    grossAreaSqm: 23573.93,
    useType: "오피스 및 업무용 빌딩",
    currentDepositPerPyeong: 110,
    currentMonthlyRentPerPyeong: 10.5,
    currentMaintenancePerPyeong: 3.6,
    occupancyRate: 98.2,
    description: "지하철 2호선 및 9호선 당산역 도보 5분 거리의 초역세권 선유동 대로변에 위치합니다. 우체국금융개발원의 밀집 지원 핵심 허브이자 다수의 공익 오피스 및 금융 협력 임차인을 유치하고 있어 강력한 임대 안정성을 구축하고 있습니다.",
    comparables: [
      {
        id: "comp-dangsan-1",
        name: "삼성생명 당산빌딩",
        address: "서울시 영등포구 양평로 21",
        builtYear: 2005,
        floors: "지하 5층 / 지상 15층",
        grossAreaSqm: 18500,
        distanceMeters: 520,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 105,
        monthlyRentPerPyeong: 10.2,
        maintenancePerPyeong: 3.4,
      },
      {
        id: "comp-dangsan-2",
        name: "당산 SK V1타워",
        address: "서울시 영등포구 선유서로 43",
        builtYear: 2015,
        floors: "지하 6층 / 지상 20층",
        grossAreaSqm: 45200,
        distanceMeters: 650,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 125,
        monthlyRentPerPyeong: 12.0,
        maintenancePerPyeong: 4.0,
      },
      {
        id: "comp-dangsan-3",
        name: "당산역 지식산업센터",
        address: "서울시 영등포구 당산동5가 9",
        builtYear: 2011,
        floors: "지하 4층 / 지상 18층",
        grossAreaSqm: 31200,
        distanceMeters: 410,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 110,
        monthlyRentPerPyeong: 10.8,
        maintenancePerPyeong: 3.5,
      },
      {
        id: "comp-dangsan-4",
        name: "여의도 파크원 타워2",
        address: "서울시 영등포구 여의대로 108",
        builtYear: 2020,
        floors: "지하 8층 / 지상 53층",
        grossAreaSqm: 162200,
        distanceMeters: 910,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 140,
        monthlyRentPerPyeong: 13.5,
        maintenancePerPyeong: 4.5,
      },
      {
        id: "comp-dangsan-5",
        name: "코오롱 디지털타워",
        address: "서울시 영등포구 선유동3로 15",
        builtYear: 2002,
        floors: "지하 3층 / 지상 11층",
        grossAreaSqm: 15800,
        distanceMeters: 280,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 98,
        monthlyRentPerPyeong: 9.6,
        maintenancePerPyeong: 3.2,
      }
    ]
  },
  {
    id: "yeongdeungpo",
    name: "영등포 우체국보험회관",
    city: "영등포",
    address: "서울특별시 영등포구 영등포동4가 425-2",
    coordinates: { x: 38, y: 35 }, // Seoul area south
    builtYear: 1988,
    floors: {
      underground: 5,
      ground: 15,
    },
    landAreaSqm: 2540,
    grossAreaSqm: 14476.76,
    useType: "오피스 및 업무용 빌딩",
    currentDepositPerPyeong: 115,
    currentMonthlyRentPerPyeong: 11.2,
    currentMaintenancePerPyeong: 3.8,
    occupancyRate: 96.5,
    description: "영등포 타임스퀘어 핵심 중심상권과 지하철 1호선 영등포역 지하 통로 연계지에 최우선 입지하고 있어, 안정적인 금융지사 임차 비중 및 우수한 집객력을 보유한 서부 서울권 핵심 거점입니다.",
    comparables: [
      {
        id: "comp-yeongdeungpo-1",
        name: "영등포 타임스퀘어 오피스A",
        address: "서울시 영등포구 영중로 15",
        builtYear: 2009,
        floors: "지하 7층 / 지상 30층",
        grossAreaSqm: 58400,
        distanceMeters: 220,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 135,
        monthlyRentPerPyeong: 12.8,
        maintenancePerPyeong: 4.2,
      },
      {
        id: "comp-yeongdeungpo-2",
        name: "영등포 리드원센터",
        address: "서울시 영등포구 국회대로 48",
        builtYear: 2013,
        floors: "지하 5층 / 지상 18층",
        grossAreaSqm: 24100,
        distanceMeters: 710,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 110,
        monthlyRentPerPyeong: 10.5,
        maintenancePerPyeong: 3.6,
      },
      {
        id: "comp-yeongdeungpo-3",
        name: "교보생명 영등포사옥",
        address: "서울시 영등포구 영등포로 188",
        builtYear: 1995,
        floors: "지하 4층 / 지상 15층",
        grossAreaSqm: 19500,
        distanceMeters: 480,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 100,
        monthlyRentPerPyeong: 9.8,
        maintenancePerPyeong: 3.2,
      },
      {
        id: "comp-yeongdeungpo-4",
        name: "케이엔포트 오피스타워",
        address: "서울시 영등포구 버드나루로 18",
        builtYear: 2000,
        floors: "지하 3층 / 지상 12층",
        grossAreaSqm: 11200,
        distanceMeters: 820,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 95,
        monthlyRentPerPyeong: 9.2,
        maintenancePerPyeong: 3.0,
      },
      {
        id: "comp-yeongdeungpo-5",
        name: "영등포 청사 빌딩",
        address: "서울시 영등포구 당산로 123",
        builtYear: 2005,
        floors: "지하 4층 / 지상 14층",
        grossAreaSqm: 14800,
        distanceMeters: 650,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 105,
        monthlyRentPerPyeong: 10.0,
        maintenancePerPyeong: 3.4,
      }
    ]
  },
  {
    id: "busan",
    name: "부산 우체국보험회관",
    city: "부산",
    address: "부산광역시 중구 중앙대로 63",
    coordinates: { x: 74, y: 83 }, // South-East
    builtYear: 1989,
    floors: {
      underground: 6,
      ground: 18,
    },
    landAreaSqm: 3100,
    grossAreaSqm: 33148.77,
    useType: "오피스 및 업무용 빌딩",
    currentDepositPerPyeong: 52,
    currentMonthlyRentPerPyeong: 5.0,
    currentMaintenancePerPyeong: 2.1,
    occupancyRate: 94.5,
    description: "부산역 및 중앙동 업무지구 핵심 대로변 코너 자산입니다. 시외 교통 접근성과 탁 트인 연안 부두 바다 조망을 확보하여 대형 행정 및 금융협회 중심 테넌트가 포진하고 있습니다.",
    comparables: [
      {
        id: "comp-busan-1",
        name: "교보생명 부산역 사옥",
        address: "부산시 동구 중앙대로 240",
        builtYear: 1998,
        floors: "지하 5층 / 지상 16층",
        grossAreaSqm: 31500,
        distanceMeters: 520,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 50,
        monthlyRentPerPyeong: 4.8,
        maintenancePerPyeong: 2.0,
      },
      {
        id: "comp-busan-2",
        name: "부산무역회관",
        address: "부산시 중구 충장대로 9",
        builtYear: 2012,
        floors: "지하 6층 / 지상 20층",
        grossAreaSqm: 27800,
        distanceMeters: 650,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 60,
        monthlyRentPerPyeong: 5.8,
        maintenancePerPyeong: 2.3,
      },
      {
        id: "comp-busan-3",
        name: "중앙동 현대생명 빌딩",
        address: "부산시 중구 중앙대로 78",
        builtYear: 1995,
        floors: "지하 4층 / 지상 12층",
        grossAreaSqm: 18500,
        distanceMeters: 210,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 45,
        monthlyRentPerPyeong: 4.2,
        maintenancePerPyeong: 1.8,
      },
      {
        id: "comp-busan-4",
        name: "대한항공 부산빌딩",
        address: "부산시 중구 중앙대로 95",
        builtYear: 2002,
        floors: "지하 4층 / 지상 15층",
        grossAreaSqm: 16200,
        distanceMeters: 380,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 48,
        monthlyRentPerPyeong: 4.5,
        maintenancePerPyeong: 1.9,
      },
      {
        id: "comp-busan-5",
        name: "한진부산종합사옥",
        address: "부산시 중구 충장대로 12",
        builtYear: 2006,
        floors: "지하 5층 / 지상 18층",
        grossAreaSqm: 41200,
        distanceMeters: 800,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 55,
        monthlyRentPerPyeong: 5.2,
        maintenancePerPyeong: 2.1,
      }
    ]
  },
  {
    id: "daegu",
    name: "대구 우체국보험회관",
    city: "대구",
    address: "대구광역시 남구 중앙대로 200",
    coordinates: { x: 67, y: 58 }, // Mid-East
    builtYear: 2003,
    floors: {
      underground: 4,
      ground: 12,
    },
    landAreaSqm: 2820,
    grossAreaSqm: 22894.63,
    useType: "오피스 및 업무용 빌딩",
    currentDepositPerPyeong: 42,
    currentMonthlyRentPerPyeong: 4.1,
    currentMaintenancePerPyeong: 1.8,
    occupancyRate: 89.2,
    description: "명덕역 더블역세권 요점과 대구 주요 중앙대로 행정 축에 긴밀하게 인접하여 양질의 오피스 공급 인프라를 지니고 있는 핵심 공적 기획 자산입니다.",
    comparables: [
      {
        id: "comp-daegu-1",
        name: "DGB대구은행 명덕지점",
        address: "대구시 남구 중앙대로 230",
        builtYear: 2005,
        floors: "지하 3층 / 지상 10층",
        grossAreaSqm: 12800,
        distanceMeters: 280,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 42,
        monthlyRentPerPyeong: 3.9,
        maintenancePerPyeong: 1.7,
      },
      {
        id: "comp-daegu-2",
        name: "삼성생명 대구남부사옥",
        address: "대구시 남구 명덕로 104",
        builtYear: 1998,
        floors: "지하 4층 / 지상 15층",
        grossAreaSqm: 19500,
        distanceMeters: 640,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 38,
        monthlyRentPerPyeong: 3.6,
        maintenancePerPyeong: 1.5,
      },
      {
        id: "comp-daegu-3",
        name: "대구 행정종합빌딩",
        address: "대구시 남구 중앙대로 180",
        builtYear: 2010,
        floors: "지하 2층 / 지상 8층",
        grossAreaSqm: 8600,
        distanceMeters: 320,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 45,
        monthlyRentPerPyeong: 4.2,
        maintenancePerPyeong: 1.8,
      },
      {
        id: "comp-daegu-4",
        name: "정부대구지방합동청사",
        address: "대구시 달서구 화암로 301",
        builtYear: 2012,
        floors: "지하 3층 / 지상 12층",
        grossAreaSqm: 46500,
        distanceMeters: 950,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 48,
        monthlyRentPerPyeong: 4.4,
        maintenancePerPyeong: 1.9,
      },
      {
        id: "comp-daegu-5",
        name: "명덕 메디컬 스퀘어",
        address: "대구시 남구 중앙대로 165",
        builtYear: 2001,
        floors: "지하 2층 / 지상 9층",
        grossAreaSqm: 6200,
        distanceMeters: 420,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 35,
        monthlyRentPerPyeong: 3.3,
        maintenancePerPyeong: 1.4,
      }
    ]
  },
  {
    id: "gwangju",
    name: "광주 우체국보험회관",
    city: "광주",
    address: "광주광역시 서구 상무중앙로 110",
    coordinates: { x: 26, y: 76 }, // South-west of map
    builtYear: 2004,
    floors: {
      underground: 4,
      ground: 12,
    },
    landAreaSqm: 2280,
    grossAreaSqm: 22400,
    useType: "오피스 및 업무용 빌딩",
    currentDepositPerPyeong: 46,
    currentMonthlyRentPerPyeong: 4.4,
    currentMaintenancePerPyeong: 1.9,
    occupancyRate: 91.8,
    description: "광주시청 및 서구 주요 공공행정타운 배후 신도시인 상무지구 중심가 랜드마크로, 지하철 상무역 역세권에 근접하여 최상의 관영 오피스 밀집 생태계를 선도하고 있습니다.",
    comparables: [
      {
        id: "comp-gwangju-1",
        name: "광주 기독교방송국 빌딩",
        address: "광주시 서구 상무중앙로 84",
        builtYear: 2010,
        floors: "지하 4층 / 지상 15층",
        grossAreaSqm: 18600,
        distanceMeters: 280,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 52,
        monthlyRentPerPyeong: 4.9,
        maintenancePerPyeong: 2.1,
      },
      {
        id: "comp-gwangju-2",
        name: "상무지구 대신증권 코너",
        address: "광주시 서구 상무중앙로 118",
        builtYear: 2000,
        floors: "지하 3층 / 지상 12층",
        grossAreaSqm: 21500,
        distanceMeters: 120,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 44,
        monthlyRentPerPyeong: 4.2,
        maintenancePerPyeong: 1.8,
      },
      {
        id: "comp-gwangju-3",
        name: "상무 현대해상 타워",
        address: "광주시 서구 상무중앙로 50",
        builtYear: 2007,
        floors: "지하 4층 / 지상 16층",
        grossAreaSqm: 28500,
        distanceMeters: 450,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 55,
        monthlyRentPerPyeong: 5.1,
        maintenancePerPyeong: 2.2,
      },
      {
        id: "comp-gwangju-4",
        name: "광주종합행정센터",
        address: "광주시 서구 치평로 25",
        builtYear: 2002,
        floors: "지하 3층 / 지상 11층",
        grossAreaSqm: 14500,
        distanceMeters: 620,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 42,
        monthlyRentPerPyeong: 4.1,
        maintenancePerPyeong: 1.7,
      },
      {
        id: "comp-gwangju-5",
        name: "상무 한국은행 빌딩",
        address: "광주시 서구 치평동 1152-1",
        builtYear: 1999,
        floors: "지하 3층 / 지상 12층",
        grossAreaSqm: 23200,
        distanceMeters: 340,
        useType: "오피스 및 업무용 빌딩",
        depositPerPyeong: 45,
        monthlyRentPerPyeong: 4.3,
        maintenancePerPyeong: 1.8,
      }
    ]
  }
];

// Conversions
export const sqmMetersToPyeong = (sqm: number) => sqm / 3.3058;
export const pyeongToSqmMeters = (pyeong: number) => pyeong * 3.3058;

// Scientifically calculate the AVM Similarity Score as specified in system instructions
export function calculateAymSimilarity(building: InsuranceBuilding, comp: ComparableBuilding): number {
  const simDist = 1 - (comp.distanceMeters / 1000);
  const simArea = 1 - (Math.abs(building.grossAreaSqm - comp.grossAreaSqm) / building.grossAreaSqm);
  const simAge = 1 - (Math.abs(building.builtYear - comp.builtYear) / 30);
  
  // Guard within [0, 1] bounds
  const sDist = Math.max(0, Math.min(1, simDist));
  const sArea = Math.max(0, Math.min(1, simArea));
  const sAge = Math.max(0, Math.min(1, simAge));
  
  // Equation weights: 0.5 Location/Distance, 0.3 Size/Area, 0.2 Age/Renovation
  return parseFloat((0.5 * sDist + 0.3 * sArea + 0.2 * sAge).toFixed(4));
}

export const defaultEstimatorConfig: Record<string, any> = {
  "dangsan": { locationWeight: 5, ageWeight: -5, sizeWeight: 2, infraWeight: 5, brandWeight: 3 },
  "yeongdeungpo": { locationWeight: 4, ageWeight: -3, sizeWeight: 2, infraWeight: 4, brandWeight: 3 },
  "busan": { locationWeight: 2, ageWeight: -2, sizeWeight: 0, infraWeight: 3, brandWeight: 2 },
  "daegu": { locationWeight: -2, ageWeight: -4, sizeWeight: -2, infraWeight: 1, brandWeight: 1 },
  "gwangju": { locationWeight: 4, ageWeight: 0, sizeWeight: -1, infraWeight: 2, brandWeight: 1 }
};

export const defaultValuationConfig: Record<string, any> = {
  "dangsan": { capRate: 4.8, vacancyRate: 3.0, operatingExpenses: 28, reconstructionUnitCost: 280, depreciationRate: 35, landUnitCostPerSqm: 3800 },
  "yeongdeungpo": { capRate: 5.0, vacancyRate: 4.0, operatingExpenses: 27, reconstructionUnitCost: 260, depreciationRate: 32, landUnitCostPerSqm: 3550 },
  "busan": { capRate: 5.5, vacancyRate: 5.5, operatingExpenses: 25, reconstructionUnitCost: 220, depreciationRate: 26, landUnitCostPerSqm: 1200 },
  "daegu": { capRate: 6.2, vacancyRate: 10.5, operatingExpenses: 25, reconstructionUnitCost: 210, depreciationRate: 22, landUnitCostPerSqm: 880 },
  "gwangju": { capRate: 6.0, vacancyRate: 8.0, operatingExpenses: 24, reconstructionUnitCost: 210, depreciationRate: 23, landUnitCostPerSqm: 950 }
};
